//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.InsideShoppingList = new HashSet<InsideShoppingList>();
            this.Orders = new HashSet<Orders>();
            this.OutsideShoppingList = new HashSet<OutsideShoppingList>();
            this.商品評論 = new HashSet<商品評論>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int Member_ID會員編號 { get; set; }
        public string MemberName會員姓名 { get; set; }
        public string Username登入帳號 { get; set; }
        public string Password登入密碼 { get; set; }
        public string Salt { get; set; }
        public string Birthyear出生年 { get; set; }
        public Nullable<System.DateTime> Birthdate出生日期 { get; set; }
        public string Phone電話 { get; set; }
        public string Address地址 { get; set; }
        public string ShippingAddress收貨地址 { get; set; }
        public byte[] M_Picture會員相片 { get; set; }
    
        public virtual ICollection<InsideShoppingList> InsideShoppingList { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<OutsideShoppingList> OutsideShoppingList { get; set; }
        public virtual Royalty Royalty { get; set; }
        public virtual ICollection<商品評論> 商品評論 { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
