//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail進貨明細
    {
        public int PurchaseOrderDetail_ID { get; set; }
        public Nullable<int> PurchaseOrder_ID進貨單號 { get; set; }
        public Nullable<int> Product_ID商品編號 { get; set; }
        public Nullable<int> Status_ID狀態編號 { get; set; }
        public Nullable<decimal> UnitPrice單價 { get; set; }
        public Nullable<int> OrderQuantity數量 { get; set; }
        public Nullable<int> ReceivedQuantity到貨量 { get; set; }
        public Nullable<System.DateTime> DueDate交期 { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual PurchaseOrder進貨單 PurchaseOrder進貨單 { get; set; }
        public virtual Status_PurchaseOrder Status_PurchaseOrder { get; set; }
    }
}
