//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder進貨單
    {
        public PurchaseOrder進貨單()
        {
            this.PurchaseOrderDetail進貨明細 = new HashSet<PurchaseOrderDetail進貨明細>();
        }
    
        public int PurchaseOrder_ID進貨單號 { get; set; }
        public Nullable<int> Vendor_ID供應商編號 { get; set; }
        public Nullable<System.DateTime> OrderDate訂貨日期 { get; set; }
        public Nullable<int> ShipMethod_ID運貨方式編號 { get; set; }
        public Nullable<decimal> ShippingFee運費 { get; set; }
        public Nullable<bool> Done { get; set; }
    
        public virtual ICollection<PurchaseOrderDetail進貨明細> PurchaseOrderDetail進貨明細 { get; set; }
        public virtual ShipMethod ShipMethod { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
