//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSAuthority
    {
        public string Employee_ID { get; set; }
        public string Program_ID { get; set; }
        public string Run { get; set; }
        public string Append { get; set; }
        public string Edit { get; set; }
        public string Report { get; set; }
    
        public virtual SSPrograms SSPrograms { get; set; }
        public virtual SSUsers SSUsers { get; set; }
    }
}
