//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_PurchaseOrder
    {
        public Status_PurchaseOrder()
        {
            this.PurchaseOrderDetail進貨明細 = new HashSet<PurchaseOrderDetail進貨明細>();
        }
    
        public int Status_ID狀態編號 { get; set; }
        public string Status狀態 { get; set; }
    
        public virtual ICollection<PurchaseOrderDetail進貨明細> PurchaseOrderDetail進貨明細 { get; set; }
    }
}
