//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class 回購週期
    {
        public 回購週期()
        {
            this.回購週期設定紀錄 = new HashSet<回購週期設定紀錄>();
        }
    
        public int Repeat_ID回購週期編號 { get; set; }
        public Nullable<byte> RepeatMonth回購週期_月_ { get; set; }
        public Nullable<byte> RepeatDay回購週期_天_ { get; set; }
    
        public virtual ICollection<回購週期設定紀錄> 回購週期設定紀錄 { get; set; }
    }
}
