//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoppingBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class 回購週期設定紀錄
    {
        public int 回_ID { get; set; }
        public Nullable<int> List_ID { get; set; }
        public Nullable<int> List_ID_Out { get; set; }
        public Nullable<int> Repeat_ID回購週期編號 { get; set; }
        public Nullable<System.DateTime> SetDate設定日 { get; set; }
    
        public virtual InsideShoppingList InsideShoppingList { get; set; }
        public virtual OutsideShoppingList OutsideShoppingList { get; set; }
        public virtual 回購週期 回購週期 { get; set; }
    }
}
