//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Member_ID { get; set; }
        public string MemberName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Birthyear { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string TelPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Address { get; set; }
        public string DeliveryAddress { get; set; }
        public string Email { get; set; }
        public byte[] M_Picture { get; set; }
        public Nullable<System.DateTime> LastDeliveryDate { get; set; }
        public string Comment { get; set; }
    }
}
